### ISSUE TITLE
Problem: Getting a property of a schema instead of the id when using belongs to

### ISSUE THREAD

**Issue by malanchito** [Codaisseur/game-project#7]
Summary:
In my `Word` schema, it belongs to a `Category` schema. On my endpoint to get all the words of a certain category I inserted include in the `findAll` function to get the name of the category instead of the id.
```
router.get('/category/:id', function (req, res, next) {
    Word
        .findAll({where:{categoryId:req.params.id}},{include:[Category]})
        .then(word => {res.json({ words: word })})
        .catch(err => {next(err)
      })
  })
```

Steps to reproduce:
1. Created Word and Category models.
2. Set `Word` to `belongTo` `Category`.
3. Queried for Words and included Categories.

Expected result:
The output shows the name of the category, not the id:
```
{
    "words": [
        {
            "category": "songs",
            "clue": "alternative song",
            "content": "the reason",
        },
    ]
}
```

Actual result:
The output only shows the id:
```
{
    "words": [
        {
            "categoryId": 1,
            "clue": "alternative song",
            "content": "the reason",
        },
    ]
}
```

**Comment by davidystephenson** [comment]
The problem was that `findAll` was passed 2 objects, the first with a `where` property and the second with an `include` property. `findAll` should only be passed 1 options object that can have both a `where` and `include` property. The correct code in this case was:
```
Word
  .findAll({
    where: { categoryId: req.params.id },
    include: [Category]
  })
```
