### ISSUE TITLE
Question: how do you declare a double-sided relation?

### ISSUE THREAD

**Issue by Fraxcelsior** [Codaisseur/game-project#9]
I am unsure on how to use hasMany properly in conjunction with belongsTo. How would I go about setting this up and return an array of, for example, userId's in a table?

(The sequelize docs are utterly unreadable and other explanations do a lot in what I think is a roundabout way)

**Comment by davidystephenson** [comment]
When declaring Sequelize relations, they should only be declared once. It does not matter which model file they are declared in. To make a double sided relation, call both `belongsTo` and `hasMany` in the same file with the arguments switched, like:
```
User.belongsTo(Game)
Game.hasMany(User)
```
